config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    #
    # Authentication
    #
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    # Settings
    #
    get 'settings' => 'settings#index'
    get 'settings/general' => 'settings#edit'
    patch 'settings' => 'settings#update'
    get 'settings/design' => 'settings#design'
    resources :users
    resources :services
    resources :service_statuses
    resources :service_groups
    resources :email_templates, :only => [:index, :edit, :update, :destroy]
    resources :api_tokens

    #
    # Issues
    #
    resources :issues do
      get 'resolved', :on => :collection
      resources :issue_updates
    end

    #
    # Maintenances
    #
    resources :maintenances do
      get 'completed', :on => :collection
      post 'toggle', :on => :member
      resources :maintenance_updates
    end

    #
    # Subscribers
    #
    resources :subscribers, :only => [:index, :destroy, :new, :create] do
      post 'verify', :on => :member
    end

    #
    # Misc. Admin Routes
    #
    get 'helpers/:action', :controller => 'helpers'

    #
    # Admin Root
    #
    root 'dashboard#index'
  end

  #
  # Setup Wizard
  #
  match 'setup/:action', :controller => 'setup', :as => 'setup', :via => [:get, :post]

  #
  # Public Site Paths
  #
  get 'issue/:id' => 'pages#issue'
  get 'maintenance/:id' => 'pages#maintenance'
  get 'history' => 'pages#history'
  get 'robots.txt' => 'pages#robots'
  get 'subscribe' => 'pages#subscribe'
  post 'subscribe/email' => 'pages#subscribe_by_email'
  get 'unsub/:token' => 'pages#unsubscribe'
  get 'verify/:token' => 'pages#subscriber_verification'
  root 'pages#index'

end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  permalink   :string(255)
#  position    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  status_id   :integer
#  description :text(65535)
#  group_id    :integer
#

class Service < ActiveRecord::Base

  validates :name, :presence => true
  validates :permalink, :presence => true, :uniqueness => true, :slug => true
  validates :status_id, :presence => true
  validates :description, :length => {:maximum => 1000}

  default_value :permalink, -> { self.name.parameterize }
  default_value :status_id, -> { ServiceStatus.default.try(:id) }
  default_value :position, -> {
    last_position = self.class.order(:position => :desc).pluck(:position).first
    self.position = last_position ? last_position + 1 : 1
  }

  belongs_to :status, :class_name => 'ServiceStatus'
  belongs_to :group, :class_name => 'ServiceGroup'
  has_many :issue_service_joins, :dependent => :destroy
  has_many :issues, :through => :issue_service_joins
  has_many :maintenance_service_joins, :dependent => :destroy
  has_many :maintenances, :through => :maintenance_service_joins
  has_many :active_maintenances, -> { references(:maintenances).where(:closed_at => nil).where("start_at <= ?", Time.now) }, :through => :maintenance_service_joins, :source => :maintenance

  scope :ordered, -> { order(:position => :asc) }

  def self.create_defaults
    Service.create!(:name => "Web Application")
    Service.create!(:name => "API")
    Service.create!(:name => "Public Website")
    Service.create!(:name => "Customer Support")
  end

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::BaseController

  before_action { params[:id] && @service = Service.find(params[:id]) }

  def index
    @services = Service.ordered.includes(:status, {:active_maintenances => :service_status})
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(safe_params)
    if @service.save
      redirect_to admin_services_path, :notice => "#{@service.name} has been added successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @service.update_attributes(safe_params)
      redirect_to admin_services_path, :notice => "#{@service.name} has been updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @service.destroy
    redirect_to admin_services_path, :notice => "#{@service.name} has been removed successfully."
  end

  private

  def safe_params
    params.require(:service).permit(:name, :permalink, :description, :status_id, :group_id)
  end

end

app/views/admin/services/_form.html.haml
= form_for [:admin, @service] do |f|
  = f.error_messages
  .fieldSet.u-margin-2x
    .row
      .col.col--10
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :name
          %dd.fieldSet__input= f.text_field :name, :class => 'textInput', :autofocus => @service.new_record?, :required => true
      .col.col--10
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :permalink
          %dd.fieldSet__input= f.text_field :permalink, :class => 'textInput', :required => true
    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :description
      %dd.fieldSet__input= f.text_area :description, :class => 'textInput'
    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :status_id, "Current Status"
      %dd.fieldSet__input
        .fieldSet__selectContainer
          = f.collection_select :status_id, ServiceStatus.all, :id, :name
    - if ServiceGroup.count > 0
      %dl.fieldSet__field.u-margin
        %dt.fieldSet__label= f.label :group_id, "Service Group"
        %dd.fieldSet__input
          .fieldSet__selectContainer
            = f.collection_select :group_id, ServiceGroup.all, :id, :name, :include_blank => true

  .formButtons
    - unless @service.new_record?
      .formButtons__secondary= link_to "Delete Service", [:admin, @service], :class => 'button button--grey button--solid', :method => :delete, :data => {:confirm => "Are you sure you wish to delete #{@service.name}?"}
    = f.submit "Save Service", :class => 'button button--solid'
    = link_to "Cancel", admin_services_path, :class => 'button button--lightGrey'

app/views/admin/services/edit.html.haml
- @active_nav_item = :settings
= content_for :page_header do
  .pageHeader__heading= @page_title = 'Edit Service'
= render 'form'

app/views/admin/services/index.html.haml
- @active_nav_item = :settings
= content_for :page_header do
  .pageHeader__button= link_to "Add New Service", new_admin_service_path, :class => 'button button--green button--small button--solid'
  .pageHeader__heading= @page_title = 'Services'

%table.dataTable.u-margin
  %thead
    %tr
      %td Name
      %td Status
      %td
  %tbody
    - for service in @services
      %tr
        %td= link_to service.name, [:edit, :admin, service], :class => 'u-underline'
        %td= service_status_tag service, :link_maintenance => :admin
        %td.u-align-right= link_to "Edit", [:edit, :admin, service], :class => 'button button--small'

app/views/admin/services/new.html.haml
- @active_nav_item = :settings
= content_for :page_header do
  .pageHeader__heading= @page_title = 'Add new service'
= render 'form'