config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    #
    # Authentication
    #
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    # Settings
    #
    get 'settings' => 'settings#index'
    get 'settings/general' => 'settings#edit'
    patch 'settings' => 'settings#update'
    get 'settings/design' => 'settings#design'
    resources :users
    resources :services
    resources :service_statuses
    resources :service_groups
    resources :email_templates, :only => [:index, :edit, :update, :destroy]
    resources :api_tokens

    #
    # Issues
    #
    resources :issues do
      get 'resolved', :on => :collection
      resources :issue_updates
    end

    #
    # Maintenances
    #
    resources :maintenances do
      get 'completed', :on => :collection
      post 'toggle', :on => :member
      resources :maintenance_updates
    end

    #
    # Subscribers
    #
    resources :subscribers, :only => [:index, :destroy, :new, :create] do
      post 'verify', :on => :member
    end

    #
    # Misc. Admin Routes
    #
    get 'helpers/:action', :controller => 'helpers'

    #
    # Admin Root
    #
    root 'dashboard#index'
  end

  #
  # Setup Wizard
  #
  match 'setup/:action', :controller => 'setup', :as => 'setup', :via => [:get, :post]

  #
  # Public Site Paths
  #
  get 'issue/:id' => 'pages#issue'
  get 'maintenance/:id' => 'pages#maintenance'
  get 'history' => 'pages#history'
  get 'robots.txt' => 'pages#robots'
  get 'subscribe' => 'pages#subscribe'
  post 'subscribe/email' => 'pages#subscribe_by_email'
  get 'unsub/:token' => 'pages#unsubscribe'
  get 'verify/:token' => 'pages#subscriber_verification'
  root 'pages#index'

end

app/models/maintenance.rb
# == Schema Information
#
# Table name: maintenances
#
#  id                :integer          not null, primary key
#  title             :string(255)
#  description       :text(65535)
#  start_at          :datetime
#  finish_at         :datetime
#  length_in_minutes :integer
#  user_id           :integer
#  service_status_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  closed_at         :datetime
#  identifier        :string(255)
#  notify            :boolean          default(FALSE)
#

class Maintenance < ActiveRecord::Base

  belongs_to :user
  belongs_to :service_status

  validates :title, :presence => true
  validates :description, :presence => true
  validates :service_status_id, :presence => true
  validates :start_at, :presence => true
  validates :finish_at, :presence => true
  validates :length_in_minutes, :numericality => {:greater_than_or_equal_to => 30, :message => "must be at least half an hour"}

  has_many :maintenance_service_joins, :dependent => :destroy
  has_many :services, :through => :maintenance_service_joins
  has_many :updates, :dependent => :destroy, :class_name => 'MaintenanceUpdate'

  random_string :identifier, :type => :uuid, :unique => true

  scope :open, -> { where(:closed_at => nil) }
  scope :closed, -> { where.not(:closed_at => nil) }
  scope :ordered, -> { order(:start_at => :asc) }
  scope :active_now, -> { where("start_at <= ?", Time.now).open }
  scope :upcoming, -> { where("start_at > ?", Time.now).open }

  before_validation :convert_times
  after_save :create_or_update_history_item
  after_destroy :destroy_history_item
  after_commit :send_notifications_on_create, :on => :create

  florrick do
    string :title
    string :description
    string :start_at
    string :finish_at
    string :length_in_minutes
    string :identifier
    string(:services) { services.map(&:name) }
    string(:duration) { length_in_minutes_as_string }
    string(:status) { I18n.translate("maintenance_statuses.#{self.status}") }
    relationship :service_status
    relationship :user
  end

  def status
    return :closed if self.closed?
    self.start_at > Time.now ? :upcoming : :active
  end

  def started?
    self.start_at < Time.now
  end

  def open?
    closed_at.nil?
  end

  def closed?
    !closed_at.nil?
  end

  def open
    self.closed_at = nil
    self.save
  end

  def close
    self.closed_at = Time.now
    self.save
  end

  def start_at_as_string
    @start_at_as_string ||= self.start_at ? self.start_at.strftime("%Y-%m-%d %H:%M") : nil
  end

  def start_at_as_string=(string)
    @start_at_as_string = string
    self.start_at = Chronic.parse(string)
  end

  def length_in_minutes_as_string
    @length_in_minutes_as_string ||= self.length_in_minutes ? ChronicDuration.output(self.length_in_minutes * 60, :format => :long) : nil
  end

  def length_in_minutes_as_string=(string)
    @length_in_minutes_as_string = string
    if string =~ /\A(\d+)\z/
      self.length_in_minutes = string.to_i
    elsif parsed_time = ChronicDuration.parse(string)
      self.length_in_minutes = parsed_time / 60
    else
      self.length_in_minutes = nil
    end
  end

  def send_notifications
    for subscriber in Subscriber.verified
      Staytus::Email.deliver(subscriber, :new_maintenance, :maintenance => self)
    end
  end

  def send_notifications_on_create
    if self.notify?
      self.delay.send_notifications
    end
  end

  private

  def convert_times
    # Set the finish time based on the start time and the
    # length of the session
    if self.start_at && self.length_in_minutes
      self.finish_at = self.start_at + (self.length_in_minutes * 60)
    end
  end

  def create_or_update_history_item
    if self.start_at_changed?
      item = HistoryItem.where(:item => self).first_or_initialize
      item.date = self.start_at
      item.save
    end
  end

  def destroy_history_item
    HistoryItem.where(:item => self).destroy_all
  end

end

app/controllers/admin/maintenances_controller.rb
class Admin::MaintenancesController < Admin::BaseController

  before_action { params[:id] && @maintenance = Maintenance.find(params[:id]) }

  def index
    @maintenances = Maintenance.open.ordered
  end

  def completed
    @maintenances = Maintenance.closed
  end

  def show
    @update = @maintenance.updates.build(:notify => true)
    @updates = @maintenance.updates.ordered
  end

  def new
    @maintenance = Maintenance.new(:notify => true)
  end

  def create
    @maintenance = Maintenance.new(safe_params)
    if @maintenance.save
      redirect_to admin_maintenances_path, :notice => "Maintenance session has been added successfully."
    else
      render 'new'
    end
  end

  def update
    if @maintenance.update(safe_params)
      redirect_to [:admin, @maintenance], :notice => "Maintenance session has been updated successfully."
    else
      render 'edit'
    end
  end

  def toggle
    if @maintenance.closed?
      @maintenance.open
      redirect_to [:admin, @maintenance], :notice => "Maintenance session has been marked as in progress successfully."
    else
      @maintenance.close
      redirect_to [:admin, @maintenance], :notice => "Maintenance session has been finished successfully."
    end
  end

  def destroy
    @maintenance.destroy
    redirect_to admin_maintenances_path, :notice => "Maintenance session has been removed successfully."
  end

  private

  def safe_params
    params.require(:maintenance).permit(:title, :description, :start_at_as_string, :length_in_minutes_as_string, :service_status_id, :notify, :service_ids => [])
  end

end

app/views/admin/maintenances/_form.html.haml
= form_for [:admin, @maintenance] do |f|
  = f.error_messages
  .fieldSet.u-margin-2x
    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :title
      %dd.fieldSet__input= f.text_field :title, :class => 'textInput', :autofocus => @maintenance.new_record?, :required => true

    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :description, "Description/schedule of works"
      %dd.fieldSet__input= f.text_area :description, :class => 'textInput'
    .row
      .col.col--12
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :start_at_as_string, "Start time (#{site.time_zone} time)"
          %dd.fieldSet__input
            .u-margin
              - if @maintenance.start_at && @maintenance.start_at_was != @maintenance.start_at
                %p.chronicPreview= @maintenance.start_at.to_s(:long)
              = f.text_field :start_at_as_string, :class => 'textInput has-chronicPreview', :required => true, :placeholder => "e.g. tomorrow at 2pm or 2015-12-23 13:40"
      .col.col--8
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :length_in_minutes_as_string, "How long will this session last?"
          %dd.fieldSet__input= f.text_field :length_in_minutes_as_string, :class => 'textInput', :required => true, :placeholder => "e.g. 2 hours, 30 minutes or 6 and a half hours"

    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :service_ids, "Which services are affected?"
      %dd.fieldSet__input
        = hidden_field_tag 'maintenance[service_ids][]', nil
        %ul.fieldSet__checkboxList
          - for service in Service.ordered
            %li
              = check_box_tag 'maintenance[service_ids][]', service.id, @maintenance.services.include?(service), :id => "service_#{service.id}"
              = label_tag "service_#{service.id}", service.name

    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :service_status_id, "Which status should be displayed for these status when this session is active?"
      %dd.fieldSet__input
        .fieldSet__selectContainer= f.collection_select :service_status_id, ServiceStatus.for_maintenance.sort_by_type, :id, :name

    - if site.allow_subscriptions?
      %dl.fieldSet__field.u-margin
        %dt.fieldSet__label= f.label :notify, "Notify subscribers when this session is posted?"
        %dd.fieldSet__input
          .fieldSet__checkbox.fieldSet__selectContainer
            = f.check_box :notify
            = f.label :notify, "Yes - send notifications to #{pluralize Subscriber.verified.count, 'subscriber'}"

  .formButtons
    - unless @maintenance.new_record?
      .formButtons__secondary= link_to "Delete", [:admin, @maintenance], :class => 'button button--solid button--grey', :method => :delete, :data => {:confirm => "Are you sure you wish to remove this session and all updates?"}

    = f.submit :class => 'button button--solid'
    = link_to "Cancel", @maintenance.new_record? ? admin_maintenances_path : [:admin, @maintenance], :class => 'button button--lightGrey'

app/views/admin/maintenances/_table.html.haml
%table.dataTable.u-margin
  %thead
    %tr
      %td{:width => '40%'} Title
      %td{:width => '40%'} Start Time
      %td{:width => '20%'} Status
  %tbody
    - for maintenance in @maintenances
      %tr
        %td= link_to maintenance.title, [:admin, maintenance], :class => 'u-underline'
        %td
          = maintenance.start_at.to_s(:short)
          for #{maintenance.length_in_minutes_as_string}
        %td= maintenance_status_tag(maintenance.status)

app/views/admin/maintenances/completed.html.haml
- @active_nav_item = :maintenance
= content_for :page_header do
  .pageHeader__button= link_to "Back", admin_maintenances_path, :class => 'button button--lightGrey button--small'
  .pageHeader__heading.u-margin= @page_title = "Completed Maintenance Sessions"
  %p.u-intro
    This page lists all maintenance sessions which are now marked as completed.

- if @maintenances.empty?
  .noDataArea.noDataArea--large
    %p.u-margin You have no completed maintenance sessions.
    %p.u-subText= link_to "Back to other sessions", admin_maintenances_path, :class => 'u-underline'
- else
  = render 'table'

app/views/admin/maintenances/edit.html.haml
- @active_nav_item = :maintenance
= content_for :page_header do
  %h1.pageHeader__heading= @page_title = 'Edit Maintenance Session'
= render 'form'

app/views/admin/maintenances/index.html.haml
- @active_nav_item = :maintenance
= content_for :page_header do
  .pageHeader__backButton= link_to "New Session", new_admin_maintenance_path, :class => 'button button--green button--solid button--small'
  .pageHeader__heading.u-margin= @page_title = "Scheduled Maintenance"
  %p.u-intro
    If you have planned maintenance on any part of your infrastructure, you can
    log it here. It will then be automatically displayed when in progress.

- if @maintenances.empty?
  .noDataArea.noDataArea--large
    %p.u-margin You have no upcoming maintenance sessions.
    %p.u-subText= link_to "Show completed sessions", completed_admin_maintenances_path, :class => 'u-underline'

- else
  = render 'table'

  %p.u-align-right= link_to "Show completed sessions", completed_admin_maintenances_path, :class => 'button button--lightGrey button--small'

app/views/admin/maintenances/new.html.haml
- @active_nav_item = :maintenance
= content_for :page_header do
  %h1.pageHeader__heading.u-margin= @page_title = 'Create a new maintenance session'
  %p.u-intro
    A maintenance session is a period of time when you are carrying out activities
    on your infrastructure which may have an impact on your service.

= render 'form'

app/views/admin/maintenances/show.html.haml
- @active_nav_item = :maintenance
= content_for :page_header do
  .pageHeader__backButton= link_to "Back to sessions", admin_maintenances_path, :class => 'button button--small button--lightGrey'
  %h1.pageHeader__heading= @page_title = "Maintenance ##{@maintenance.id}"

.u-margin
  %dl.definition.u-margin
    %dt Title
    %dd= @maintenance.title
  %dl.definition.u-margin
    %dt Details
    %dd= @maintenance.description
  %dl.definition.u-margin
    %dt Time Period
    %dd
      = @maintenance.start_at.to_s(:long)
      for #{@maintenance.length_in_minutes_as_string}
  %dl.definition.u-margin
    %dt Completion Time
    %dd= @maintenance.finish_at.to_s(:long)
  %dl.definition.u-margin
    %dt Status
    %dd= maintenance_status_tag @maintenance.status
  - unless @maintenance.services.empty?
    %dl.definition.u-margin
      %dt Affected Services
      %dd
        %ul.standardList.standardList--double
          - for service in @maintenance.services
            %li= service.name
  %dl.definition.u-margin-2x
    %dd.buttonSet
      - if @maintenance.open?
        = link_to "Finish Session", [:toggle, :admin, @maintenance], :class => 'button button--small button--green button--solid', :method => :post
      - else
        = link_to "Re-open Session", [:toggle, :admin, @maintenance], :class => 'button button--small button--lightGrey button--solid', :method => :post
      = link_to "Edit Details", [:edit, :admin, @maintenance], :class => 'button button--small'

.box.box--white
  = form_for [:admin, @maintenance, @update] do |f|
    .fieldSet
      %dl.fieldSet__field.u-margin
        %dt.fieldSet__label= f.label :text, "Post an update"
        %dd.fieldSet__field= f.text_area :text, :class => 'textInput', :placeholder => "Enter the text you wish to post here..."

      - if @maintenance.notify? && site.allow_subscriptions?
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :notify, "Notify subscribers when this session is posted?"
          %dd.fieldSet__input
            .fieldSet__checkbox.fieldSet__selectContainer
              = f.check_box :notify
              = f.label :notify, "Yes - send notifications to #{pluralize Subscriber.verified.count, 'subscriber'}"

      %p.u-align-right= f.submit "Post Update", :class => 'button button--solid'

  .box__footer
    %ul.issueUpdates
      - if @updates.empty?
        .noDataArea There are no updates for this session.
      - else
        - for update in @updates
          %li.issueUpdates__item
            %p.issueUpdates__text= update.text
            %p.issueUpdates__meta
              Posted #{time_tag update.created_at}
              - if update.user
                by #{update.user.name}
              = link_to "Edit", [:edit, :admin, @maintenance, update], :class => 'u-underline issueUpdates__edit'