config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    #
    # Authentication
    #
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    # Settings
    #
    get 'settings' => 'settings#index'
    get 'settings/general' => 'settings#edit'
    patch 'settings' => 'settings#update'
    get 'settings/design' => 'settings#design'
    resources :users
    resources :services
    resources :service_statuses
    resources :service_groups
    resources :email_templates, :only => [:index, :edit, :update, :destroy]
    resources :api_tokens

    #
    # Issues
    #
    resources :issues do
      get 'resolved', :on => :collection
      resources :issue_updates
    end

    #
    # Maintenances
    #
    resources :maintenances do
      get 'completed', :on => :collection
      post 'toggle', :on => :member
      resources :maintenance_updates
    end

    #
    # Subscribers
    #
    resources :subscribers, :only => [:index, :destroy, :new, :create] do
      post 'verify', :on => :member
    end

    #
    # Misc. Admin Routes
    #
    get 'helpers/:action', :controller => 'helpers'

    #
    # Admin Root
    #
    root 'dashboard#index'
  end

  #
  # Setup Wizard
  #
  match 'setup/:action', :controller => 'setup', :as => 'setup', :via => [:get, :post]

  #
  # Public Site Paths
  #
  get 'issue/:id' => 'pages#issue'
  get 'maintenance/:id' => 'pages#maintenance'
  get 'history' => 'pages#history'
  get 'robots.txt' => 'pages#robots'
  get 'subscribe' => 'pages#subscribe'
  post 'subscribe/email' => 'pages#subscribe_by_email'
  get 'unsub/:token' => 'pages#unsubscribe'
  get 'verify/:token' => 'pages#subscriber_verification'
  root 'pages#index'

end

app/models/email_template.rb
# == Schema Information
#
# Table name: email_templates
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  subject    :string(255)
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EmailTemplate < ActiveRecord::Base

  validates :name, :presence => true
  validates :subject, :presence => true
  validates :content, :presence => true

  def self.body_for(name)
    if template = self.where(:name =>name).select(:content).first
      template.content
    end
  end

  def self.subject_for(name)
    if template = self.where(:name =>name).select(:subject).first
      template.subject
    end
  end

end

app/controllers/admin/email_templates_controller.rb
class Admin::EmailTemplatesController < Admin::BaseController

  def index
    @templates = EmailTemplate.pluck(:name)
  end

  def edit
    @default = I18n.translate("email_templates")[params[:id].to_sym]
    raise Status::Error, "Invalid template name" unless @default.is_a?(Hash)
    @default_content = File.read(Rails.root.join("app", "views", "emails", "#{params[:id]}.txt"))
    @template = EmailTemplate.find_by_name(params[:id])
    @template = EmailTemplate.new(:name => params[:id]) if @template.nil?
  end

  def update
    edit
    @template.attributes = params.require(:email_template).permit(:subject, :content)
    if @template.save
      redirect_to admin_email_templates_path, :notice => "#{@default[:name]} has been updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @template = EmailTemplate.find_by_name!(params[:id])
    @template.destroy
    redirect_to admin_email_templates_path, :notice => "Template has been reverted successfully."
  end

end

app/views/admin/email_templates/edit.html.haml
- @active_nav_item = :settings
- content_for :page_header do
  %h1.pageHeader__heading= @page_title = "Edit #{@default[:name]}"

= form_for @template, :method => :patch, :url => admin_email_template_path(params[:id]), :html => {:class => 'u-margin-2x'} do |f|
  = f.error_messages
  .fieldSet
    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :subject
      %dd.fieldSet__input= f.text_field :subject, :class => 'textInput', :placeholder => @default[:default_subject]
    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :content, "Message"
      %dd.fieldSet__text
        You should use markdown to format your outbound messages. You can also use the variables
        below to insert appropriate text. Outbound messages will be formatted with the template
        defined in your theme.
      %dd.fieldSet__input= f.text_area :content, :class => 'textInput textInput--text', :placeholder => @default_content

  .formButtons
    - unless @template.new_record?
      .formButtons__secondary
        = link_to "Revert to default", admin_email_template_path(@template.name), :class => 'button button--grey button--solid', :method => :delete, :data => {:confirm => "Are you sure you wish to revert to the default content?"}
    = f.submit "Save Template", :class => 'button button--solid'
    = link_to "Cancel", admin_email_templates_path, :class => 'button button--lightGrey'


.variableList
  %p.u-intro.u-margin
    You can use the variables shown below in your message content or subject.
    The variable sets which are available depends on the e-mail which you editting.
  .row.u-margin
    .col.col--10
      %h2.variableList__heading Issue
      %ul.variableList__list
        - for field in Issue.florrick_fields.values.flatten.map(&:keys).flatten
          %li {{issue.#{field}}}
    .col.col--10
      %h2.variableList__heading Issue Update
      %ul.variableList__list
        - for field in IssueUpdate.florrick_fields.values.flatten.map(&:keys).flatten
          %li {{update.#{field}}}
  .row.u-margin
    .col.col--10
      %h2.variableList__heading Maintenance Session
      %ul.variableList__list
        - for field in Maintenance.florrick_fields.values.flatten.map(&:keys).flatten
          %li {{maintenance.#{field}}}
    .col.col--10
      %h2.variableList__heading Maintenance Update
      %ul.variableList__list.u-margin
        - for field in MaintenanceUpdate.florrick_fields.values.flatten.map(&:keys).flatten
          %li {{update.#{field}}}
      %h2.variableList__heading Service Status
      %ul.variableList__list
        - for field in ServiceStatus.florrick_fields.values.flatten.map(&:keys).flatten
          %li {{status.#{field}}}

  .row.u-margin
    .col.col--10
      %h2.variableList__heading User
      %ul.variableList__list
        - for field in User.florrick_fields.values.flatten.map(&:keys).flatten
          %li {{user.#{field}}}
    .col.col--10
      %h2.variableList__heading Subscriber
      %ul.variableList__list
        - for field in Subscriber.florrick_fields.values.flatten.map(&:keys).flatten
          %li {{subscriber.#{field}}}

  .row.u-margin
    .col.col--10
      %h2.variableList__heading Site
      %ul.variableList__list
        - for field in Site.florrick_fields.values.flatten.map(&:keys).flatten
          %li {{site.#{field}}}

app/views/admin/email_templates/index.html.haml
- @active_nav_item = :settings
- content_for :page_header do
  %h1.pageHeader__heading.u-margin= @page_title = 'E-Mail Templates'
  %p.u-intro
    From here you can customize the contents of any of the emails sent to people
    who subscribe to your status site by e-mail.

%table.dataTable
  %thead
    %tr
      %td{:width => '80%'} Template
      %td{:width => '20%'}
  %tbody
    - for name, template in t("email_templates")
      %tr
        %td= template[:name]
        %td.u-align-right= link_to (@templates.include?(name.to_s) ? "Edit" : "Add"), edit_admin_email_template_path(name), :class => 'button button--small'