config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    #
    # Authentication
    #
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    # Settings
    #
    get 'settings' => 'settings#index'
    get 'settings/general' => 'settings#edit'
    patch 'settings' => 'settings#update'
    get 'settings/design' => 'settings#design'
    resources :users
    resources :services
    resources :service_statuses
    resources :service_groups
    resources :email_templates, :only => [:index, :edit, :update, :destroy]
    resources :api_tokens

    #
    # Issues
    #
    resources :issues do
      get 'resolved', :on => :collection
      resources :issue_updates
    end

    #
    # Maintenances
    #
    resources :maintenances do
      get 'completed', :on => :collection
      post 'toggle', :on => :member
      resources :maintenance_updates
    end

    #
    # Subscribers
    #
    resources :subscribers, :only => [:index, :destroy, :new, :create] do
      post 'verify', :on => :member
    end

    #
    # Misc. Admin Routes
    #
    get 'helpers/:action', :controller => 'helpers'

    #
    # Admin Root
    #
    root 'dashboard#index'
  end

  #
  # Setup Wizard
  #
  match 'setup/:action', :controller => 'setup', :as => 'setup', :via => [:get, :post]

  #
  # Public Site Paths
  #
  get 'issue/:id' => 'pages#issue'
  get 'maintenance/:id' => 'pages#maintenance'
  get 'history' => 'pages#history'
  get 'robots.txt' => 'pages#robots'
  get 'subscribe' => 'pages#subscribe'
  post 'subscribe/email' => 'pages#subscribe_by_email'
  get 'unsub/:token' => 'pages#unsubscribe'
  get 'verify/:token' => 'pages#subscriber_verification'
  root 'pages#index'

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController

  def edit
    @site = Site.find(site.id)
  end

  def design
    @site = Site.find(site.id)
  end

  def update
    @site = Site.find(site.id)
    if @site.update_attributes(params.require(:site).permit(:title, :domain, :description, :support_email, :website_url, :time_zone, :http_protocol, :crawling_permitted, :allow_subscriptions, :email_from_name, :email_from_address, :logo_file, :logo_delete, :cover_image_file, :cover_image_delete, :privacy_policy_url))
      redirect_to redirection_path_for(params[:return_to]), :notice => "Settings have been saved successfully."
    else
      render form_render_for(params[:return_to])
    end
  end

  private

  def form_render_for(return_to)
    case return_to
    when 'design' then 'design'
    else 'edit'
    end
  end

  def redirection_path_for(return_to)
    case return_to
    when 'design' then admin_settings_design_path
    else admin_settings_path
    end
  end

end

app/views/admin/settings/design.html.haml
- @active_nav_item = :design_settings
= content_for :page_header do
  %h1.pageHeader__heading.u-margin= @page_title = "Design settings"
  %p.u-intro
    From here you can customize aspects of your status page's design.
    If you are using a using a custom theme, you may find that some of these
    options are not supported.

= form_for @site, :url => admin_settings_path do |f|
  = hidden_field_tag 'return_to', 'design'
  = f.error_messages
  .fieldSet.u-margin-2x
    .row.u-margin-2x
      .col.col--12
        %dl.fieldSet__field
          %dt.fieldSet__label= f.label :logo_file, "Upload a logo"
          %dd.fieldSet__text
            It's recommended that your logo is less than 100x50 pixels and is as small as possible.
          %dd.fieldSet__input
            .fieldSet__selectContainer= f.file_field :logo_file
      .col.col--8
        - if @site.logo
          .imagePreview
            = link_to "Delete", '#'
            = image_tag @site.logo.path
            = f.hidden_field :logo_delete
        - else
          .imagePreview.imagePreview--empty
            No logo

    .row
      .col.col--12
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :cover_image_file, "Upload a cover image"
          %dd.fieldSet__text
            It's recommended that cover images are around 1500x1000 pixels and are as compressed
            as possible without losing too much image quality.
          %dd.fieldSet__input
            .fieldSet__selectContainer= f.file_field :cover_image_file
      .col.col--8
        - if @site.cover_image
          .imagePreview
            = link_to "Delete", '#'
            = image_tag @site.cover_image.path
            = f.hidden_field :cover_image_delete
        - else
          .imagePreview.imagePreview--empty
            No cover image

  .formButtons
    = f.submit "Save Settings", :class => 'button button--solid'
    = link_to "Cancel", admin_settings_path, :class => 'button button--lightGrey'

app/views/admin/settings/edit.html.haml
- @active_nav_item = :settings
= content_for :page_header do
  %h1.pageHeader__heading.u-margin= @page_title = "General Settings"
  %p.u-intro
    This form allows you to make changes to your general settings. Once you have made
    your changes, just click the 'Save' button at the bottom to continue.

= form_for @site, :url => admin_settings_path do |f|
  = f.error_messages
  .fieldSet.u-margin-2x
    .row
      .col.col--10
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :title
          %dd.fieldSet__input= f.text_field :title, :class => 'textInput'
      .col.col--10
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :domain
          %dd.fieldSet__input= f.text_field :domain, :class => 'textInput'

    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :description
      %dd.fieldSet__input= f.text_area :description, :class => 'textInput'

    .row
      .col.col--10
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :support_email, "Support E-Mail Addresss"
          %dd.fieldSet__input= f.text_field :support_email, :class => 'textInput'
      .col.col--10
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :website_url, "Website URL"
          %dd.fieldSet__input= f.text_field :website_url, :class => 'textInput'

    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :time_zone, "Time Zone"
      %dd.fieldSet__input
        .fieldSet__selectContainer
          = f.time_zone_select :time_zone
    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :http_protocol, "HTTP Protocol"
      %dd.fieldSet__input
        .fieldSet__selectContainer
          = f.select :http_protocol, [['HTTP', 'http'], ['HTTPS', 'https']]

    %dl.fieldSet__field.u-margin-2x
      %dt.fieldSet__label= f.label :crawling_permitted, "Allow search engines?"
      %dd.fieldSet__input
        .fieldSet__checkbox.fieldSet__selectContainer
          = f.check_box :crawling_permitted
          = f.label :crawling_permitted, "Yes - allow search engines to index the public status site"

    %dl.fieldSet__field.u-margin-2x
      %dt.fieldSet__label= f.label :allow_subscriptions, "Allow visitors to subscribe to your status site?"
      %dd.fieldSet__input
        .fieldSet__checkbox.fieldSet__selectContainer
          = f.check_box :allow_subscriptions
          = f.label :allow_subscriptions, "Yes - allow visitors to receive updates whenever you add/update issues"
    %dl.fieldSet__field.u-margin-2x
      %dt.fieldSet__label= f.label :privacy_policy_url, "Privacy Policy URL"
      %dd.fieldSet__input= f.text_field :privacy_policy_url, :class => 'textInput'


    %h2.fieldSet__subHeading.u-margin Outgoing E-Mail Settings
    .row
      .col.col--10
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :email_from_name, "Outgoing E-Mail Name"
          %dd.fieldSet__input= f.text_field :email_from_name, :class => 'textInput', :placeholder => @site.title
      .col.col--10
        %dl.fieldSet__field.u-margin
          %dt.fieldSet__label= f.label :email_from_address, "Outgoing E-Mail Address"
          %dd.fieldSet__input= f.text_field :email_from_address, :class => 'textInput', :placeholder => @site.support_email



  .formButtons
    = f.submit "Save Settings", :class => 'button button--solid'
    = link_to "Cancel", admin_settings_path, :class => 'button button--lightGrey'

app/views/admin/settings/index.html.haml
- @active_nav_item = :settings
= content_for :page_header do
  %h1.pageHeader__heading.u-margin= @page_title = "Staytus Settings"
  %p.u-intro
    Your settings are split into a number of areas. Choose from the options
    below to choose which settings you wish to edit.

.navGrid.u-margin-2x
  .navGrid__item
    = image_tag 'icons/general.svg'
    %p= link_to "General Settings", admin_settings_general_path
    %p.navGrid__text Manage your site name, contact details, outbound email settings and other general settings.
  .navGrid__item
    = image_tag 'icons/design.svg'
    %p= link_to "Design", admin_settings_design_path
    %p.navGrid__text Upload your own logo and cover image which is displayed on your public status site.
.navGrid.u-margin-2x
  .navGrid__item
    = image_tag 'icons/users.svg'
    %p= link_to "Users", admin_users_path
    %p.navGrid__text Create admin users who are able to manage your site and add/update issues & maintenance sessions.
  .navGrid__item
    = image_tag 'icons/services.svg'
    %p= link_to "Services", admin_services_path
    %p.navGrid__text Configure the services which you'd like to report the statuses of.
.navGrid.u-margin-2x
  .navGrid__item
    = image_tag 'icons/statuses.svg'
    %p= link_to "Service Statuses", admin_service_statuses_path
    %p.navGrid__text Configure the different statuses which can be assigned to the services you're reporting on.
  .navGrid__item
    = image_tag 'icons/services.svg'
    %p= link_to "Service Groups", admin_service_groups_path
    %p.navGrid__text Configure the different groups which can be assigned to the services you're reporting on.
.navGrid
  .navGrid__item
    = image_tag 'icons/api_tokens.svg'
    %p= link_to "API Tokens", admin_api_tokens_path
    %p.navGrid__text Manage which external applications are permitted to access your status site using the API.
  .navGrid__item
    = image_tag 'icons/email_templates.svg'
    %p= link_to "E-Mail Templates", admin_email_templates_path
    %p.navGrid__text Customize the content of the emails which are sent to people who subscribe to your site by e-mail.